### ISSUE TITLE
Needs Development

### ISSUE THREAD

**Issue by brooketowle** [brooketowle/colemanwebsite#2]
Start developing his site. Note: Don't forget to make the phone number clickable on all browsers!

**Comment by AnthonyDeveloper** [comment]
Fatal Site Crash. Occurred when making phone number clickable. I give up. I quit.

**Comment by brooketowle** [comment]
WIKI WIKI! Client need's the website in 2 weeks!

**Comment by AnthonyDeveloper** [comment]
EXTREME PANIC MODE ACTIVATED

**Comment by AnthonyDeveloper** [comment]
It's up to me. now.....

**Comment by AnthonyDeveloper** [comment]
A miracle occurred and I got the code to WORK! I forgot to put a <!-- infront of a comment. :D
